---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- route.yaml

# Three notes here:
# 1. The BuildConfig was not kicked off automatically, but the lab makes it seem like everything should work from the beginning
# 2. I ran the BuildConfig manually and the resulting image did not work
# 3. Separate from the image not working I had to use the full image url `image-registry.openshift-image-registry.svc:5000/quarkus-superheroes-user1/rest-fights` to get it to work
# although changing the image stream to `lookupPolicy.local` should also work in theory.
patches:

- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rest-fights
    spec:
      template:
        spec:
          containers:
            - name: rest-fights
              image: rest-fights:latest

- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: rest-fights-config
    data:
      quarkus.smallrye-openapi.servers: http://unknown:8080
